services:
  - type: web
    name: hera-palace-api
    runtime: python
    plan: free
    region: frankfurt
    rootDir: hera-backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hera-palace-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_CALLBACK_URL
        sync: false

databases:
  - name: hera-palace-db
    plan: free
    region: frankfurt
